### ISSUE TITLE
deprecated task execution handler

### ISSUE THREAD

**Issue by cyptus** [laser-cake/AssemblyVersionLoader#4]
Version 1.0.9 throws a warning because of an deprecated task execution handler:

`##[warning]Task 'AssemblyVersionLoader' (1.0.9) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib`

https://aka.ms/tasklib

**Comment by AppiePau** [comment]
Hi cyptus, I'm sorry to inform you that won't bw able to fix this soon. I'm also considering to abandon this project due to other priorities. You are welcome to take ownership over from me or someone else.

**Comment by laser-cake** [comment]
Hi AppiePau, I'll have a go at upgrading the task execution handler and try testing it on my own repo (full disclosure, I'm not entirely sure what I'm doing, but I'll give it a go)  Seems a shame to abandon this project.

Cheers

**Comment by AppiePau** [comment]
Awesome, let me know how it goes. Good luck!

**Comment by laser-cake** [comment]
I've managed to upgrade to the latest task version, it was a bit more involved than I originally thought. I still need to tweak the prefix variable. I'll fix that and I'll get a PR ready in the next few days.

**Comment by laser-cake** [comment]
All done, quite a lot of change stuff needed to be added, but the powershell script itself is mostly the same.

[https://github.com/AppiePau/AssemblyVersionLoader/pull/6](url)

**Comment by AppiePau** [comment]
Great to see you are getting along and making results!

**Comment by laser-cake** [comment]
Do you still want to abandon this project? If so, I'm happy to take ownership. I'm not sure how that works! :)

Cheers.

**Comment by AppiePau** [comment]
Sure, I can transfer ownership to you. If you are planning to publish this extension to the public Marketplace of Visual Studio / TFS I would like you to do it on your own behalf/publisher name. I'm not sure if this is possible since it has already been published under my name.

**Comment by laser-cake** [comment]
Brilliant thanks. Yes I'm planning to publish, I think I might just have to create a new version. I'll have a look :)

**Comment by AppiePau** [comment]
Alright, I will now transfer ownership to you. Take good care of my baby 😁

**Comment by AppiePau** [comment]
Bummer:
"laser-cake/AssemblyVersionLoader already exists"

We should probably merge your version with mine and then delete your version, so I can retry the transfer again. Or just delete your version from github. Let me know what works best for you.

**Comment by laser-cake** [comment]
Might be better to merge first and then transfer (so we don't lose the update). I'll delete my repo now, so you can transfer when you can :)

Update: Deletion done

**Comment by AppiePau** [comment]
Excuse my late response. I have initiated the transfer. I guess you should receive some notification.

**Comment by laser-cake** [comment]
Looks like it worked. I'll get an update version out at some point in the next few days! Thanks Mate.

**Comment by AppiePau** [comment]
Yes, I see! It's on your account now. Good luck with the future development!

**Comment by laser-cake** [comment]
Finally published, please install the following version:

https://marketplace.visualstudio.com/items?itemName=AshStansfield.AssemblyVersionLoader

**Comment by AppiePau** [comment]
Awesome! You even managed to take over ownership on the VS Marketplace

**Comment by laser-cake** [comment]
Oh wow, I didn't think that would happen! Haha
